name: CI

on: [push]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependent libraries
        run: sudo apt-get install -y libpq-dev
      - name: Set up Ruby and run bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Show Ruby version
        run: ruby -v
      - name: Prepare database and run tests
        run: |
          env
          bash v1.sh
